### PR TITLE
fix import path in resolvers

### PR DESCRIPTION
**Pull request by Weakky**

### CODE REVIEW

**Comment by Weakky** [comment]
@kevinmarrec It should, yes!

**Comment by kevinmarrec** [comment]
@Weakky Is it available in `0.2.0-beta16` ? If yes I just tried it and I still have
```js
import { Resolvers } from "./src/generated/graphqlgen.ts";
```
instead of
```js
import { Resolvers } from "../generated/graphqlgen";
```

**Comment by Weakky** [comment]
It is not published yet, wait until tomorrow or use master if you want to try it out

**Comment by kevinmarrec** [comment]
Yeah my bad, just seen that the two PR I was waiting for were just merged after last NPM publish :)

Will try it tomorrow ! Thank you for quick answers and thank your for your work, you guys are amazing :)

**Pull request merged**
