### PR TITLE
export enums to allow implementations conforming to them

### PR DESCRIPTION
**Pull request by koenpunt**
Without the enums being exported, it's not possible to create an implementation that conforms to the type, without casting to `any` (or redeclaring the full enum).

Fixes: #315

### CODE REVIEW

**Comment by Weakky** [comment]
Hey koenpunt 👋,

Could you provide a simple example where you need to import an enum from `graphqlgen.ts` to implement a resolver?

**Comment by koenpunt** [comment]
For example, in the screenshot below the resolver is generated with `UserGender` as the return type, which is a generated enum. But conforming to that type is now only possible by declaring the type again outside of the generated types.

image

Also here the issue is marked as a bug: https://github.com/prisma/graphqlgen/issues/315

**Comment by jasonkuhrt** [comment]
> But conforming to that type is now only possible by declaring the type again outside of the generated types.

@koenpunt I am not against exporting at all, support it, however I would like to still better understand. Could you provide a code snippet, can be made up pseudo code, showing what your implementation would look like once this feature lands?

Thanks 🙏 !

**Comment by arianon** [comment]
I want this so I can do type-safe switch statements, something like this.

```graphql
type Query {
  products(orderBy: Order!): [Product!]!
}

enum Order {
  BESTSELLING
  NEWEST
  OLDEST
  ALPHABETIC
  HIGHESTPRICE
  LOWESTPRICE
}
```
```ts
import { Product } from "../types";
import { QueryResolvers } from "../generated/graphqlgen";

const Query: QueryResolvers.Type = {
  async game(parent, { orderBy }) {
    switch (order) {
      case "BESTSELLING": // ...
      case "NEWEST": // ...
      case "OLDEST": // ...
      // I want TS to throw a type error if I forget a possible value.
    }
  }
};

export default { Query };
```

**Comment by jasonkuhrt** [comment]
@arianon thanks for your example!

**Pull request merged**
